name: nft_marketplace
description: A new Flutter application.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  confetti: ^0.6.0-nullsafety
  flare_flutter: ^3.0.2
  video_player: ^2.1.12
  fl_chart: ^0.36.3
  flutter_svg: ^0.22.0
  funvas: ^0.1.3+5
  cached_network_image: ^3.1.0
  transparent_image: ^2.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/flares/
     - assets/

